development:
  adapter: postgresql
  encoding: unicode
  database: prueba
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5433

test:
  adapter: postgresql
  encoding: unicode
  database: prueba
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5433

production:
  adapter: postgresql
  encoding: unicode
  database: prueba
  pool: 5
  username: postgres
  password: postgres
  host: localhost
  port: 5433
